### PR TITLE
an alter way to run index.html, only a go http server

### PR DESCRIPTION
**Pull request by farwish**

### CODE REVIEW

**Comment by drazdra** [comment]
hi, nice to see you!

from what i see, you import a lot of various libraries to make this work. i don't know go, so i don't know what's going on there, 

the reason for this UI was was to make it as private as possible, with as little imports as possible, to avoid any potential risks of losing "privacy" with importing some spyware. 

running any small webservers (there are tons of these) or importing some modules, is potentially risk of import the spyware or installing security holes. while i can trust nginx, i can't trust something custom. 

if you believe adding go webserver is good, i suggest you to make a project for cloning with the files of your go mod. then i can add to readme a few lines of yours, letting people know how to install your mod, if they have go and and trust your code, they can git clone your mod and use it instead of nginx. it's going to be their choice then :).

**Comment by farwish** [comment]
> hi, nice to see you!
> 
> from what i see, you import a lot of various libraries to make this work. i don't know go, so i don't know what's going on there,
> 
> the reason for this UI was was to make it as private as possible, with as little imports as possible, to avoid any potential risks of losing "privacy" with importing some spyware.
> 
> running any small webservers (there are tons of these) or importing some modules, is potentially risk of import the spyware or installing security holes. while i can trust nginx, i can't trust something custom.
> 
> if you believe adding go webserver is good, i suggest you to make a project for cloning with the files of your go mod. then i can add to readme a few lines of yours, letting people know how to install your mod, if they have go and and trust your code, they can git clone your mod and use it instead of nginx. it's going to be their choice then :).

Sure, you are right.  And a README of simple usage be here https://github.com/farwish/ollama-chats/tree/main/go
Again thanks your project.

**Comment by drazdra** [comment]
i've updated the readme file with a link to your repo.

**Comment by farwish** [comment]
> i've updated the readme file with a link to your repo.

Just realized that nodejs is installed,  maybe nodejs can make launch step easier.
And a README of simple usage be here https://github.com/farwish/ollama-chats/tree/main/node
Again thanks your nice project.

**Comment by drazdra** [comment]
node is a huge thing with loads of contributors, there are known cases of code wiping your data and doing other fun things, not mentioning classical stealing of data. i would certainly not recommend anybody installing node for just running a single html file :). 

i might add a small transparent one file web-server in the future, but i don't feel it's important, considering how secure nginx is and how easy it is to install it. comparing nginx to node for this task is like 100:1 in my personal opinion.

**Pull request closed without merging**
